name: Build Python Module
on: [workflow_dispatch, pull_request]
jobs:
  build-module:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Build binary wheel
        run: python setup.py sdist
      
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_api_key }}
          repository_url: https://test.pypi.org/legacy/